name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'python'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run test
        run: |
          polyglot --jvm --coverage --coverage.Output=lcov --coverage.OutputFile=coverage.lcov run.js
      
      - name:  Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: './coverage.lcov'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: './coverage.lcov'
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
